from backend.services.embedding import create_embedding, EMBEDDING_MODEL
from backend.services.similarity import cosine_similarity
from backend.repositories.knowledge_embedding_repository import get_all_embeddings


def search_knowledge(
    question: str,
    top_k: int = 3
) -> list[dict]:
    """
    Retrieve the most relevant knowledge records
    using embedding-based semantic similarity.
    """

    # Generate an embedding for the user question
    question_vector = create_embedding(question)

    # Retrieve stored embeddings
    embeddings = get_all_embeddings()

    results = []

    for item in embeddings:

        # Skip embeddings generated by a different model
        if item["Model"] != EMBEDDING_MODEL:
            continue

        score = cosine_similarity(
            question_vector,
            item["Vector"]
        )

        results.append(
            {
                "KnowledgeId": item["KnowledgeId"],
                "Score": score
            }
        )

    # Sort by similarity score in descending order
    results.sort(
        key=lambda x: x["Score"],
        reverse=True
    )

    return results[:top_k]